version: 2
jobs:
  execute:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn install
      - run: node app.js
      - run: git config --global user.email "jrawebapp@xilab.org"
      - run: git config --global user.name "handson-llc"
workflows:
  version: 2
  execute-workflow:
    triggers:
      - schedule:
          cron: '0 1 * * 1,5' # UTC
          filters:
            branches:
              only:
                - main
    jobs:
      - execute
